# Generated by Django 5.2.5 on 2025-08-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('replied', 'Replied')], default='new', max_length=10)),
                ('reply', models.TextField(blank=True, null=True)),
                ('screated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
