# Generated by Django 5.2.5 on 2025-08-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='screated_at',
            new_name='created_at',
        ),
    ]
