# Generated by Django 5.2.8 on 2025-11-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_screated_at_message_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='reply',
            new_name='response',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
