# Generated by Django 5.1.3 on 2025-05-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Contactinfo',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
