# Generated by Django 5.1.3 on 2025-05-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_delete_about_delete_contactinfo_delete_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
